name: Deploy Portfolio Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Use the version that matches your project

      # Step 3: Install dependencies and build the Astro.js project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 4: Deploy using rsync
      - name: Deploy using rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Configure SSH for rsync
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add server's host key to known_hosts to prevent SSH prompt
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

          # Use rsync to transfer only the contents of 'dist' directory
          rsync -avz --delete-after dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/amir/apps/amirazmi

      # Optional: Cleanup SSH key
      - name: Cleanup
        run: rm -rf ~/.ssh/id_rsa
